[project]
name = "livecodebench-pro"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=3.6.0",
    "docker>=7.1.0",
    "huggingface-hub>=0.35.0",
    "openai>=1.108.1",
    "tqdm>=4.67.1",
]
